---
grupo_nombre: "ILoveLinux Colo"
division: "División 318"
integrantes:
  - nombre: "Valentin"
    apellido: "D'Adamo"
  - nombre: "Santino"
    apellido: "Casado"
  - nombre: "Leandro"
    apellido: "Archenzio"

