# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "primero" do |vmHost1|
    vmHost1.vm.box = "ubuntu/jammy64"
    vmHost1.vm.hostname = "vmHost1"
    vmHost1.vm.network "private_network", ip: "192.168.56.4"
    
    vmHost1.vm.synced_folder 'compartido_Host1/', '/home/vagrant/compartido', 
      owner: 'vagrant', group: 'vagrant' 

    vmHost1.ssh.insert_key = true
    # Agrego un nuevo disco 
    vmHost1.vm.disk :disk, size: "5GB", name: "#{vmHost1.vm.hostname}_extra_storage"
    vmHost1.vm.disk :disk, size: "3GB", name: "#{vmHost1.vm.hostname}_extra_storage2"
    vmHost1.vm.disk :disk, size: "2GB", name: "#{vmHost1.vm.hostname}_extra_storage3"
    vmHost1.vm.disk :disk, size: "1GB", name: "#{vmHost1.vm.hostname}_extra_storage4"

    vmHost1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "vmHost1"
      vb.cpus = 1
      vb.linked_clone = true
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
    end    

    vmHost1.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vmHost1.vm.provision "shell", path: "instala_paquetes.sh"
    vmHost1.vm.provision "shell", privileged: false, inline: <<-SHELL
      mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
      git clone https://github.com/upszot/UTN-FRA_SO_Ansible.git
      git clone https://github.com/upszot/UTN-FRA_SO_Docker.git
      cd ..
      git clone --branch dev https://github.com/JoniBe/TP_AySO_Integral_Las_Mitocondrias
      mkdir -p /home/vagrant/script_folders
      cd /home/vagrant/script_folders
      git clone https://github.com/giulianolol/script.git
      cd /home/vagrant/script_folders/script
      chmod +x script_cross_visudo_hosts.sh
      chmod +x script_discos.sh
    SHELL
  end
    
  config.vm.define :segundo do |vmHost2|
    vmHost2.vm.box = "fedora/37-cloud-base"
    vmHost2.vm.hostname = "vmHost2"
    vmHost2.vm.network "private_network", ip: "192.168.56.5"
    
    vmHost2.vm.synced_folder 'compartido_Host2/', '/home/vagrant/compartido'
    
    vmHost2.ssh.insert_key = true
    vmHost2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "vmHost2"
      vb2.cpus = 1
      vb2.linked_clone = true
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    
    vmHost2.vm.provision "shell", path: "script_Enable_ssh_password.sh"

    vmHost2.vm.provision "shell", run: "always", inline: <<-SHELL
      sudo ip addr add 192.168.56.5/22 dev eth1 || true
    SHELL
      
    vmHost2.vm.provision "shell", inline: <<-SHELL
      dnf install -y /home/vagrant/compartido/tree-1.8.0-10.el9.x86_64.rpm
      dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      dnf install -y git

      mkdir -p /home/vagrant/script_folders
      cd /home/vagrant/script_folders
      sudo git clone https://github.com/giulianolol/script_fedora.git
      sudo git clone --branch dev https://github.com/JoniBe/TP_AySO_Integral_Las_Mitocondrias
      cd /home/vagrant/script_folders/script_fedora
      sudo chmod +x script_cross_visudo_hosts.sh
    SHELL
  end
end
