# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "test" do |vmtest|
    vmtest.vm.box = "ubuntu/jammy64"
    vmtest.vm.hostname = "vmtest"
    vmtest.vm.network "private_network", ip: "192.168.56.4"
    
    vmtest.vm.synced_folder 'compartido_test/', '/home/vagrant/compartido', 
      owner: 'vagrant', group: 'vagrant' 

    vmtest.ssh.insert_key = true
    # Agrego un nuevo disco 
    vmtest.vm.disk :disk, size: "5GB", name: "#{vmtest.vm.hostname}_extra_storage"
    vmtest.vm.disk :disk, size: "3GB", name: "#{vmtest.vm.hostname}_extra_storage2"
    vmtest.vm.disk :disk, size: "2GB", name: "#{vmtest.vm.hostname}_extra_storage3"
    vmtest.vm.disk :disk, size: "1GB", name: "#{vmtest.vm.hostname}_extra_storage4"

    vmtest.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "vmtest"
      vb.cpus = 1
      vb.linked_clone = true
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']      
    end    

    vmtest.vm.provision "shell", path: "script_Enable_ssh_password.sh"
    vmtest.vm.provision "shell", path: "instala_paquetes.sh"
    vmtest.vm.provision "shell", privileged: false, inline: <<-SHELL
      mkdir -p /home/vagrant/repogit
      cd /home/vagrant/repogit
      git clone https://github.com/upszot/UTN-FRA_SO_onBording.git 
      git clone https://github.com/upszot/UTN-FRA_SO_Ansible.git
      git clone https://github.com/upszot/UTN-FRA_SO_Docker.git
      git clone https://github.com/upszot/2do_Parcial.git
      cd ..
      git clone https://github.com/ValenDadamo/TP_AySO_Integral_ILoveLinux_Colo.git
      mkdir -p /home/vagrant/script_folders
      cd /home/vagrant/script_folders
      git clone https://github.com/ValenDadamo/TP_AySO_Integral_Scripts.git
      cd /home/vagrant/script_folders/TP_AySO_Integral_Scripts
      chmod +x script_cross_visudo_hosts.sh
      chmod +x script_discos.sh

    SHELL
  end
    
  config.vm.define :prod do |vmprod|
    vmprod.vm.box = "fedora/37-cloud-base"
    vmprod.vm.hostname = "vmprod"
    vmprod.vm.network "private_network", ip: "192.168.56.5"
    
    vmprod.vm.synced_folder 'compartido_prod/', '/home/vagrant/compartido'
    
    vmprod.ssh.insert_key = true
    vmprod.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.name = "vmprod"
      vb2.cpus = 1
      vb2.linked_clone = true
      vb2.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
    end
    
    vmprod.vm.provision "shell", path: "script_Enable_ssh_password.sh"

    vmprod.vm.provision "shell", run: "always", inline: <<-SHELL
      sudo ip addr add 192.168.56.5/22 dev eth1 || true
    SHELL
      
    vmprod.vm.provision "shell", inline: <<-SHELL
      dnf install -y /home/vagrant/compartido/tree-1.8.0-10.el9.x86_64.rpm
      dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
      dnf install -y git

      mkdir -p /home/vagrant/script_folders
      cd /home/vagrant/script_folders
      sudo git clone https://github.com/ValenDadamo/TP_AySO_Integral_Scripts_Fedora.git
      sudo git clone https://github.com/ValenDadamo/TP_AySO_Integral_ILoveLinux_Colo.git
      cd /home/vagrant/script_folders/TP_AySO_Integral_Scripts_Fedora
      sudo chmod +x script_cross_visudo_hosts.sh
    SHELL
  end
end
